#!/bin/bash

# Your job name
#$ -N recurrence

# The job should be placed into the queue 'all.q'
#$ -q all.q

# Running in the current directory
#$ -cwd

# Export some necessary environment variables
#$ -v PATH
#$ -v LD_LIBRARY_PATH
#$ -v PYTHONPATH
#$ -S /bin/bash

for f in *.fastq;
do
       	fastqc $f;
done

multiqc .;

#trimming51
java -jar /data4/nextgen2015/users/17235058/thesis/recurrence/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 8 -phred33 \
-trimlog /data4/nextgen2015/users/17235058/thesis/recurrence/recurrenceHN51.trimlog \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN51_S3_recur.BD1LYPACXX.lane_5_P1_I13.hg19.sequence.fastq \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN51_S3_recur.BD1LYPACXX.lane_5_P2_I13.hg19.sequence.fastq \
HN51_S3_recur.BD1LYPACXX.lane_5_P1_I13_For_PAIRED.fastq \
HN51_S3_recur.BD1LYPACXX.lane_5_P1_I13_For_UnPAIRED.fastq \
HN51_S3_recur.BD1LYPACXX.lane_5_P2_I13_Rev_PAIRED.fastq \
HN51_S3_recur.BD1LYPACXX.lane_5_P2_I13_Rev_UnPAIRED.fastq \
ILLUMINACLIP:Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:36

#trim60
java -jar /data4/nextgen2015/users/17235058/thesis/recurrence/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 8 -phred33 \
-trimlog /data4/nextgen2015/users/17235058/thesis/recurrence/recurrenceHN60.trimlog \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN60_s3_recurrence.BD1LYPACXX.lane_8_P1_I18.hg19.sequence.fastq \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN60_s3_recurrence.BD1LYPACXX.lane_8_P2_I18.hg19.sequence.fastq \
HN60_s3_recurrence.BD1LYPACXX.lane_8_P1_I18.For_paired.fastq \
HN60_s3_recurrence.BD1LYPACXX.lane_8_P1_I18.For_Unpaired.fastq \
HN60_s3_recurrence.BD1LYPACXX.lane_8_P2_I18_Rev_PAIRED.fastq \
HN60_s3_recurrence.BD1LYPACXX.lane_8_P2_I18_Rev_UnPAIRED.fastq \
ILLUMINACLIP:Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:36

#trim72AC
java -jar /data4/nextgen2015/users/17235058/thesis/recurrence/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 8 -phred33 \
-trimlog /data4/nextgen2015/users/17235058/thesis/recurrence/recurrenceHN72AC.trimlog \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN72s3.AC254KACXX.lane_3_P1_I16.hg19.sequence.fastq \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN72s3.AC254KACXX.lane_3_P2_I16.hg19.sequence.fastq \
HN72s3.AC254KACXX.lane_3_P1_I16.hg19.sequence.For_paired.fastq \
HN72s3.AC254KACXX.lane_3_P1_I16.hg19.sequence.For_Unpaired.fastq \
HN72s3.AC254KACXX.lane_3_P2_I16.hg19.sequence_Rev_PAIRED.fastq \
HN72s3.AC254KACXX.lane_3_P2_I16.hg19.sequence_Rev_UnPAIRED.fastq \
ILLUMINACLIP:Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:36

#trimHN72AH
java -jar /data4/nextgen2015/users/17235058/thesis/recurrence/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads 8 -phred33 \
-trimlog /data4/nextgen2015/users/17235058/thesis/recurrence/recurrenceHN72AH.trimlog \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN72s3.AH0LENADXX.lane_2_P1_I16.hg19.sequence.fastq \
/home/nextgen2015/class2018/17235058/thesis/recurrence/HN72s3.AH0LENADXX.lane_2_P2_I16.hg19.sequence.fastq \
HN72s3.AH0LENADXX.lane_2_P1_I16.hg19.sequence.For_paired.fastq \
HN72s3.AH0LENADXX.lane_2_P1_I16.hg19.sequence.For_Unpaired.fastq \
HN72s3.AH0LENADXX.lane_2_P2_I16.hg19.sequence_Rev_PAIRED.fastq \
HN72s3.AH0LENADXX.lane_2_P2_I16.hg19.sequence_Rev_UnPAIRED.fastq \
ILLUMINACLIP:Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:36

#mapping51
bwa mem -M -t 8 -R '@RG\tID:BD1LYPACXX.3\tSM:HN52\tLB:I12' hg19.fa HN51_S3_recur.BD1LYPACXX.lane_5_P1_I13_For_PAIRED.fastq \
HN51_S3_recur.BD1LYPACXX.lane_5_P2_I13_Rev_PAIRED.fastq | samtools view -Sb - > HN51.recur.bam

#mapping60
bwa mem -M -t 8 -R '@RG\tID:BD1LYPACXX.3\tSM:HN52\tLB:I12' hg19.fa HN60_s3_recurrence.BD1LYPACXX.lane_8_P1_I18.For_paired.fastq \
HN60_s3_recurrence.BD1LYPACXX.lane_8_P2_I18_Rev_PAIRED.fastq | samtools view -Sb - > HN60.recur.bam

#mapping72AC
bwa mem -M -t 8 -R '@RG\tID:BD1LYPACXX.3\tSM:HN52\tLB:I12' hg19.fa HN72s3.AC254KACXX.lane_3_P1_I16.hg19.sequence.For_paired.fastq \
HN72s3.AC254KACXX.lane_3_P2_I16.hg19.sequence_Rev_PAIRED.fastq | samtools view -Sb - > HN72AC.recur.bam

#map72AH
bwa mem -M -t 8 -R '@RG\tID:BD1LYPACXX.3\tSM:HN52\tLB:I12' hg19.fa HN72s3.AH0LENADXX.lane_2_P1_I16.hg19.sequence.For_paired.fastq \
HN72s3.AH0LENADXX.lane_2_P2_I16.hg19.sequence_Rev_PAIRED.fastq | samtools view -Sb - > HN72AH.recur.bam


java -jar picard.jar AddOrReplaceReadGroups \
I=HN51.recur.bam \
O=HN51.recur.RG.bam \
RGLB=I12 \
RGPL=illumina \
RGPU=unit2 \
RGSM=HN51_recur \
RGID=BD1LYPACXX.3

java -jar picard.jar AddOrReplaceReadGroups \
I=HN60.recur.bam \
O=HN60.recur.RG.bam \
RGLB=I12 \
RGPL=illumina \
RGPU=unit2 \
RGSM=HN60_recur \
RGID=BD1LYPACXX.3


java -jar picard.jar AddOrReplaceReadGroups \
I=HN72AC.recur.bam \
O=HN72AC.recur.RG.bam \
RGLB=I12 \
RGPL=illumina \
RGPU=unit2 \
RGSM=HN72AC_recur \
RGID=BD1LYPACXX.3

java -jar picard.jar AddOrReplaceReadGroups \
I=HN72AH.recur.bam \
O=HN72AH.recur.RG.bam \
RGLB=I12 \
RGPL=illumina \
RGPU=unit2 \
RGSM=HN72AH_recur \
RGID=BD1LYPACXX.3

#sort sam
java -jar picard.jar SortSam \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN51.recur.RG.bam \
O=HN51.sorted.recur.bam \
SORT_ORDER=coordinate

java -jar picard.jar SortSam \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN60.recur.RG.bam \
O=HN60.sorted.recur.bam \
SORT_ORDER=coordinate

java -jar picard.jar SortSam \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN72AC.recur.RG.bam \
O=HN72AC.sorted.recur.bam \
SORT_ORDER=coordinate

java -jar picard.jar SortSam \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN72AH.recur.RG.bam \
O=HN72AH.sorted.recur.bam \
SORT_ORDER=coordinate

#mark duplicates

java -jar picard.jar MarkDuplicates \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN51.sorted.recur.bam \
O=HN51.dedup_reads.bam \
METRICS_FILE=metrics.HN51_R.txt

java -jar picard.jar MarkDuplicates \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN60.sorted.recur.bam \
O=HN60.dedup_reads.bam \
METRICS_FILE=metrics.HN60_R.txt

java -jar picard.jar MarkDuplicates \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN72AC.sorted.recur.bam \
O=HN72AC.dedup_reads.bam \
METRICS_FILE=metrics.HN72AC_R.txt

java -jar picard.jar MarkDuplicates \
TMP_DIR=./ \
MAX_RECORDS_IN_RAM=2000000 \
I=HN72AH.sorted.recur.bam \
O=HN72AH.dedup_reads.bam \
METRICS_FILE=metrics.HN72AH_R.txt

# BQSR

java -jar gatk-package-4.0.2.1-local.jar \
BaseRecalibrator \
--TMP_DIR=./ \
-R hg19.fa \
-I HN51.dedup_reads.bam \
--known-sites dbsnp_138.hg19.vcf \
--known-sites Mills_and_1000G_gold_standard.indels.hg19.sites.vcf \
-O recal_HN51.table

java -jar gatk-package-4.0.2.1-local.jar \
ApplyBQSR \
-R hg19.fa \
-I HN51.dedup_reads.bam \
--bqsr-recal-file recal_HN51.table \
-O HN51.dedup_reads.bqsr.bam

java -jar gatk-package-4.0.2.1-local.jar \
BaseRecalibrator \
--TMP_DIR=./ \
-R hg19.fa \
-I HN60.dedup_reads.bam \
--known-sites dbsnp_138.hg19.vcf \
--known-sites Mills_and_1000G_gold_standard.indels.hg19.sites.vcf \
-O recal_HN60.table

java -jar gatk-package-4.0.2.1-local.jar \
ApplyBQSR \
-R hg19.fa \
-I HN60.dedup_reads.bam \
--bqsr-recal-file recal_HN60.table \
-O HN60.dedup_reads.bqsr.bam

java -jar gatk-package-4.0.2.1-local.jar \
BaseRecalibrator \
--TMP_DIR=./ \
-R hg19.fa \
-I HN72.dedup_reads.bam \
--known-sites dbsnp_138.hg19.vcf \
--known-sites Mills_and_1000G_gold_standard.indels.hg19.sites.vcf \
-O recal_HN72.table

java -jar gatk-package-4.0.2.1-local.jar \
ApplyBQSR \
-R hg19.fa \
-I HN72.dedup_reads.bam \
--bqsr-recal-file recal_HN72.table \
-O HN72.dedup_reads.bqsr.bam

# mutect

java -jar gatk-package-4.0.2.1-local.jar Mutect2 \
-R hg19.fa \
-I HN51.dedup_reads.bqsr.recurrence.bam \
-tumor HN51_recur \
-I HN51.dedup_reads.bqsr.normal.bam \
-normal HN52 \
-pon threesamplepon.vcf.gz \
-L SeqCap_EZ_Exome_v3_hg19_primary_targets.bed \
-O HN51_recurrence_somatic.vcf.gz

java -jar gatk-package-4.0.2.1-local.jar Mutect2 \
-R hg19.fa \
-I HN60.dedup_reads.bqsr.recurrence.bam \
-tumor HN60_recur \
-I HN60.dedup_reads.bqsr.normal.bam \
-normal HN60 \
-pon threesamplepon.vcf.gz \
-L SeqCap_EZ_Exome_v3_hg19_primary_targets.bed \
-O HN60_recurrence_somatic.vcf.gz


java -jar gatk-package-4.0.2.1-local.jar Mutect2 \
-R hg19.fa \
-I HN72.dedup_reads.bqsr.recurrence.bam \
-tumor HN72_recur \
-I HN72.dedup_reads.bqsr.normal.bam \
-normal HN72 \
-pon threesamplepon.vcf.gz \
-L SeqCap_EZ_Exome_v3_hg19_primary_targets.bed \
-O HN72_recurrence_somatic.vcf.gz

# filter mutect calls
# HN51
java -jar gatk-package-4.0.2.1-local.jar GetPileupSummaries \
-I HN51.dedup_reads.bqsr.recurrence.bam \
-V threesamplepon.vcf \
-O HN51r_getpileupsummaries.table

java -jar gatk-package-4.0.2.1-local.jar CalculateContamination \
-I HN51r_getpileupsummaries.table \
-O HN51r_contamination.table

java -jar gatk-package-4.0.2.1-local.jar FilterMutectCalls \
-V HN51_recurrence_somatic.vcf \
-contamination-table HN51r_contamination.table \
-O HN51_recurrence_somatic_filtered.vcf

#HN60
java -jar gatk-package-4.0.2.1-local.jar GetPileupSummaries \
-I HN60.dedup_reads.bqsr.recurrence.bam \
-V threesamplepon.vcf \
-O HN60r_getpileupsummaries.table

java -jar gatk-package-4.0.2.1-local.jar CalculateContamination \
-I HN60r_getpileupsummaries.table \
-O HN60r_contamination.table

java -jar gatk-package-4.0.2.1-local.jar FilterMutectCalls \
-V HN60_recurrence_somatic.vcf \
-contamination-table HN60r_contamination.table \
-O HN60_recurrence_somatic_filtered.vcf

#HN72
java -jar gatk-package-4.0.2.1-local.jar GetPileupSummaries \
-I HN72.dedup_reads.bqsr.recurrence.bam \
-V threesamplepon.vcf \
-O HN72r_getpileupsummaries.table

java -jar gatk-package-4.0.2.1-local.jar CalculateContamination \
-I HN72r_getpileupsummaries.table \
-O HN72r_contamination.table

java -jar gatk-package-4.0.2.1-local.jar FilterMutectCalls \
-V HN72_recurrence_somatic.vcf \
-contamination-table HN72r_contamination.table \
-O HN72_recurrence_somatic_filtered.vcf


